language: java
sudo: false # faster builds

jdk:
    - oraclejdk8
    - openjdk7

script:
    - travis_wait 30 mvn clean package
    - travis_wait 30 mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
